#!/bin/bash

dir="$PWD"
if [ -L ~/.i3 ]; then
    rm ~/.i3
    ln -sv "$dir"/i3 ~/.i3
fi   
ln -svf "$dir"/pentadactylrc ~/.pentadactylrc

mkdir -p ~/.config/gtk-3.0
ln -svf "$dir/settings.ini" ~/.config/gtk-3.0/settings.ini 
ln -svf "$dir/gtkrc-2.0" ~/."gtkrc-2.0"


